metagenomix create \
  -i metagenomix/tests/example/fastqs_illumina \
  -m metagenomix/tests/example/metadata/meta.txt \
  -o metagenomix/tests/example/output \
  -p metagenomix/tests/example/pipeline/pipeline_red4.txt \
  -d metagenomix/tests/example/configs/databases.yml \
  -c metagenomix/tests/example/configs/coassembly.yml \
  -u metagenomix/tests/example/configs/user_params.yml \
  -M metagenomix/tests/example/configs/modules.yml \
  --dev \
  -n test \
  --force
