coconet:
  algorithm: leiden
  batch_size: 256
  chunks: 4
  compo_neurons:
  - 64
  - 32
  continue: false
  cover_filters: 16
  cover_kernel: 4
  cover_neurons:
  - 64
  - 32
  cover_stride: 2
  cpus: 1
  debug: 20
  env: null
  features: coveragecomposition
  flag: 3596
  fragment_length: -1
  fragment_step: 128
  gamma1: 0.3
  gamma2: 0.4
  kmer: 4
  learning_rate: 0.001
  load_batch: 100
  machine: null
  max_neighbors: 250
  mem: 10
  mem_dim: gb
  merge_neurons: 32
  min_aln_coverage: 50
  min_ctg_len: 2048
  min_dtr_size: 10
  min_mapping_quality: 30
  min_prevalence: 2
  n_clusters: 0
  n_frags: 30
  n_test: 10000
  n_train: 4000000
  no_rc: false
  nodes: 1
  partition: null
  patience: false
  quiet: false
  recruit_small_contigs: false
  scratch: scratch
  silent: false
  test_batch: 400
  test_ratio: 0.1
  theta: 0.8
  time: 24
  tlen_range: []
  vote_threshold: 0
  wsize: 64
  wstep: 32
