# -------------------- Follow the format examples below -------------------- #
#my_database_name: /a/path/to/the/folder/containing/my/database              #
#                                                                            #
#  for the tools that ship with a database, such as humann, wol, midas, etc, #
#  then this must be the path where the database is installed, but if you    #
#  have created re-formatted versions of these databases (or others), then   #
#  this path must contain the formatting sub-folders (as explained  above)   #
# -------------------------------------------------------------------------- #

# human pangenomes for filtering
CHM13Y: /cluster/shared/databases/references/Homo_sapiens/HPRC/2023-09-21/databases/CHM13Y
HG002.1: /cluster/shared/databases/references/Homo_sapiens/HPRC/2023-09-21/databases/HG002.1
HG002.2: /cluster/shared/databases/references/Homo_sapiens/HPRC/2023-09-21/databases/HG002.2
HG00438.1: /cluster/shared/databases/references/Homo_sapiens/HPRC/2023-09-21/databases/HG00438.1
HG00438.2: /cluster/shared/databases/references/Homo_sapiens/HPRC/2023-09-21/databases/HG00438.2
HG005.1: /cluster/shared/databases/references/Homo_sapiens/HPRC/2023-09-21/databases/HG005.1
HG005.2: /cluster/shared/databases/references/Homo_sapiens/HPRC/2023-09-21/databases/HG005.2
HG00621.1: /cluster/shared/databases/references/Homo_sapiens/HPRC/2023-09-21/databases/HG00621.1

# general dbs
pfam: /cluster/projects/nn8075k/03_databases/Pfam/2024-10-05

# tools dbs
dbcan: /cluster/projects/nn8075k/03_databases/dbCAN
midas: /cluster/projects/nn8075k/03_databases/midas_db_v1.2/2016-11-02
platon: /cluster/projects/nn8075k/03_databases/platon
ioncom: /cluster/projects/nn8075k/03_databases/IonCom
metaxa2: /cluster/projects/nn8075k/softwares/Metaxa2_2.2.3/metaxa2_db
macsyfinder: /cluster/projects/nn8075k/03_databases/macsyfinder
squeezemeta: /cluster/projects/nn9745k/03_databases/SqueezeMeta
humann: /cluster/shared/databases/metaphlan3/latest
metaphlan: /cluster/shared/databases/metaphlan3/latest
midas2_gtdb: /cluster/shared/databases/MIDAS2/latest/gtdb
checkm: /cluster/shared/biobases/classification_dbs/checkm_data_2015_01_16
gtdbtk: /cluster/shared/databases/gtdb/2022-06-20/auxillary_files/gtdbtk_r207_v2_data
uniref: /cluster/shared/databases/uniprot/latest/uniref90
wol: /cluster/shared/databases/wol/latest
# kraken2
k2_standard: /cluster/shared/databases/Kraken2/2023-09-10/standard

# builds
tara_mags: /cluster/shared/databases/tara_oceans/latest/TaraOceans_BAC_ARC_MAGs
tara_smags: /cluster/shared/databases/tara_oceans/latest/TaraOceans_SMAGs
oceandna_rep: /cluster/shared/databases/tara_oceans/latest/OceanDNA_MAGs/databases/oceandna_rep
rep82: /cluster/shared/databases/SHOGUN/latest/rep82/
my_algae_database: /cluster/shared/databases/custom/algae_database
