fastp:
  cut_right: true
  cpus: 16
  chunks: 12
  mem: 15
  scratch: scratch

filtering:
  aligner: bowtie2
  databases:
  - CHM13Y
  - HG002.1
  - HG002.2
  - HG00438.1
  - HG00438.2
  chunks: 5
  mem: 30
  time: 160
  cpus: 16

simka:
  path: C:\folder\where\to\install\softwares\simka-v1.5.3-bin-Linux
  kmer:
    start: 50
    end: 100
    size: 3
  log_reads:
    start: 4
    end: 7
    size: 3
  mem: 10
  scratch: userscratch
  simkaMin: yes
  env: qiime2-2023.5
  machine: saga
  cpus: 16

flash:
  min_overlap: 10
  max_overlap: 100
  mismatch: 0
  time: 24
  cpus: 6
  mem: 5
  chunks: 8

kraken2:
  time: 200
  mem: 400
  partition: bigmem
  scratch: userscratch
  chunks: 4
  cpus: 12
  confidence: 0.8
  databases:
    - k2_standard
    - tara_mags
    #- my_algea_database

bracken:
  scratch: scratch
  mem: 3
  chunks: 36
  cpus: 12
  path: C:\folder\where\to\install\softwares\Bracken
  read_len: 100
  time: 48

megahit:
  mem: 300
  chunks: 1
  partition: bigmem
  cpus: 24
  time: 200
  scratch: scratch

prodigal:
  p: meta
  env: metagenomics
  machine: saga
  time: 48
  mem: 20

eggnogmapper:
  chunks: 1
  cpus: 16
  data_dir: C:\folder\where\to\install\databases\eggnog-mapper-data
  env: eggnog-mapper
  dbmem: yes
  machine: saga
  mem: 80
  scratch: 100
  time: 100

